server:
  port: 8080
  read_timeout: "5s"
  write_timeout: "10s"
  idle_timeout: "10s"

database:
  host: postgres # postgres - Docker, localhost - local
  port: "5432"
  user: postgres
  password: ""
  name: auth
  ssl_mode: disable

logger:
  level: "info"
  json: false

migrations:
  dir: "migrations/postgres"

jwt:
  expiry: "24h"
  secret_key: ""